log:
  path: ./
  filesize: 10485760
  filenumber: 10
local:
  listen: 0.0.0.0:8090
  timeout: 30
  auth:
    - username: user1
      password: uS31k5KLh3NyfvHtFk
    - username: user2
      password: c2O9XJGG0bsJLpt6tr
  mode: proxy
  tls:
    enable: true
remote:
  - address: 192.168.0.1:8080
    timeout: 30
    tls:
      enable: true